name: Release

on:
  release:
    types: [published]
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  release:
    permissions:
      contents: write
    secrets:
      RABE_PYPI_TOKEN: ${{ secrets.RABE_PYPI_TOKEN }}
    uses: radiorabe/actions/.github/workflows/release-python-poetry.yaml@v0.40.0
